spring.application.name=taskmanager

# Configuración de la Base de Datos H2
spring.datasource.url=jdbc:h2:mem:taskdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Habilitar la consola web de H2 (Muy útil para desarrollo)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# ddl-auto=update crea y actualiza las tablas automáticamente basándose en Task.java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true